# Generated by Django 2.0.9 on 2019-02-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramboard', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
