# Generated by Django 2.0.9 on 2019-06-15 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSECourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cse_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CSECourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='csecourses.CSECourse')),
            ],
        ),
        migrations.CreateModel(
            name='CSECourseGroupTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csecourses.CSECourseGroup')),
            ],
        ),
        migrations.CreateModel(
            name='CSETerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='csecoursegroupterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='csecourses.CSETerm'),
        ),
    ]
