# Generated by Django 2.0.9 on 2018-12-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csecourses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csecourse',
            name='cse_id',
            field=models.CharField(max_length=255),
        ),
    ]
