# Generated by Django 2.0.9 on 2018-12-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csecourses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cseterm',
            name='title',
            field=models.CharField(default='97 1st', max_length=255),
            preserve_default=False,
        ),
    ]
