# Generated by Django 2.0.9 on 2018-12-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csecourses', '0002_auto_20181228_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSECourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csecourses.CSECourse')),
            ],
        ),
    ]
