# Generated by Django 2.0.9 on 2019-01-26 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csecourses', '0002_cseterm_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csecoursegroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='csecourses.CSECourse'),
        ),
    ]
