# Generated by Django 2.0.9 on 2018-12-28 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csecourses', '0003_csecoursegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSECourseGroupTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csecourses.CSECourse')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='csecourses.CSETerm')),
            ],
        ),
    ]
