# Generated by Django 2.0.9 on 2018-12-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csecourses', '0004_csecoursegroupterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cseterm',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cseterm',
            name='start',
            field=models.DateField(),
        ),
    ]
