# Generated by Django 2.0.9 on 2019-06-15 21:16

import campaigns.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('csecourses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10000, null=True)),
                ('type', enumfields.fields.EnumField(enum=campaigns.models.CampaignType, max_length=1000)),
                ('course_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csecourses.CSECourseGroupTerm')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignPartyRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_request_note', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('type', enumfields.fields.EnumField(enum=campaigns.models.CampaignPartyRelationType, max_length=1000)),
                ('status', enumfields.fields.EnumField(enum=campaigns.models.CampaignPartyRelationStatus, max_length=1000)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cprelations', to='campaigns.Campaign')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='campaigns.Campaign')),
            ],
        ),
    ]
