# Generated by Django 2.0.9 on 2018-12-29 00:22

import campaigns.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('csecourses', '__first__'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10000, null=True)),
                ('type', enumfields.fields.EnumField(enum=campaigns.models.CampaignType, max_length=1000)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, height_field='height_field', null=True, upload_to=campaigns.models.campaign_image_upload_location, width_field='width_field')),
                ('banner_image', models.ImageField(blank=True, height_field='banner_height_field', null=True, upload_to=campaigns.models.campaign_image_upload_location, width_field='banner_width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('banner_width_field', models.IntegerField(default=0)),
                ('banner_height_field', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('course_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csecourses.CSECourseGroupTerm')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignPartyRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('type', enumfields.fields.EnumField(enum=campaigns.models.CampaignPartyRelationType, max_length=1000)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('slug', 'type')},
        ),
    ]
