# Generated by Django 2.0.9 on 2019-01-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignpartyrelation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='enrollment_request_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
