# Generated by Django 2.0.9 on 2019-01-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_enrollment_request_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='enrollment_request_note',
        ),
        migrations.AddField(
            model_name='campaignpartyrelation',
            name='enrollment_request_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
