# Generated by Django 2.0.9 on 2019-01-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20190123_0757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='banner_height_field',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='banner_width_field',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='description',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='image',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='title',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='width_field',
        ),
    ]
