# Generated by Django 2.0.9 on 2019-06-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20190126_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='campaigns.Campaign')),
            ],
        ),
    ]
