# Generated by Django 2.0.9 on 2019-06-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaignsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='title',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
