# Generated by Django 2.0.9 on 2019-06-15 21:16

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import qualification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_qualifications', to='campaigns.CampaignPartyRelation')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_qualifications', to='campaigns.CampaignPartyRelation')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('result_body', models.TextField()),
                ('type', enumfields.fields.EnumField(enum=qualification.models.QuestionType, max_length=1000)),
                ('coeff', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionQualificationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qualification.QualificationForm')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='qualification.Question')),
            ],
        ),
        migrations.AddField(
            model_name='qa',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qualification.Qualification'),
        ),
        migrations.AddField(
            model_name='qa',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qualification.QuestionQualificationRelation'),
        ),
    ]
