# Generated by Django 2.0.9 on 2018-12-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('questions', models.ManyToManyField(to='qualification.Question')),
            ],
        ),
    ]
