# Generated by Django 2.0.9 on 2019-01-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0002_qualificationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionQualificationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='qualificationform',
            name='questions',
        ),
        migrations.AddField(
            model_name='questionqualificationrelation',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qualification.QualificationForm'),
        ),
        migrations.AddField(
            model_name='questionqualificationrelation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='qualification.Question'),
        ),
    ]
