# Generated by Django 2.0.9 on 2019-01-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0003_auto_20190102_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qualification.QuestionQualificationRelation'),
        ),
    ]
