# Generated by Django 2.0.9 on 2019-02-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190116_1249'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='detail',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='resources.Publisher'),
        ),
        migrations.RemoveField(
            model_name='detail',
            name='translator',
        ),
        migrations.AddField(
            model_name='detail',
            name='translator',
            field=models.ManyToManyField(related_name='detail', to='users.Profile'),
        ),
    ]
