# Generated by Django 2.0.9 on 2019-02-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20190226_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.Profile'),
        ),
    ]
