# Generated by Django 2.0.9 on 2019-03-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20190226_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksuggestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookSuggestion',
        ),
    ]
